apiVersion: esx.vmware.com/v1alpha1
kind: HostConfiguration
metadata:
  name: monitoring-user
  namespace: esx-system
spec:
  layertype: SystemBase
  profile: |
    {
      "esx": {
        "authentication": {
          "user_accounts": [
            {
              "name": "monitor",
             "password": "Lucky0916!@",
              "description": "Monitoring user account"
            }
          ]
        },
        "authorization": {
          "permissions": [
            {
              "principal": "monitor",
              "is_group": false,
              "access_mode": "ReadOnly"
            }
          ]
        }
      }
    }
