apiVersion: esx.vmware.com/v1alpha1
kind: HostConfiguration
metadata:
  name: keswick-host-config
  namespace: esx-system
spec:
  layertype: Incremental
  profile: |
    {
      "esx": {
        "system": {
          "system_time": {
            "enabled": false,
            "protocol": "NTP",
            "ntp_config": {
              "server": [{
                  "hostname": "8.8.8.8",
                  "command": "SERVER"
                },
                {
                  "hostname": "0.pool.ntp.org",
                  "command": "SERVER"
                }
              ]
            }
          }
        }
      }
    }
