apiVersion: esx.vmware.com/v1alpha1
kind: HostConfiguration
metadata:
  name: welcome-message
  namespace: esx-system
spec:
  layertype: new
  profile: |
    {
      "esx": {
          "system": {
            "welcome_message": {
                "message": "!!!!!!VMware Edge Cloud Orchestrator - Edge Host!!!!"
            }
          }
      }
    }
